### PR TITLE
Upload slides from MDAnalysis team presentations

### PR DESCRIPTION
**Pull request by jennaswa**
This PR would upload presentation slides for UGM talks given my MDAnalysis core devs. Namely:

- Welcome and Opening Remarks @orbeckst 
- MDAnalysis State of the Union @richardjgowers 
- Closing Remarks @orbeckst 
- A Bird's Eye View of Contributing to and Maintaining Open Source Software @fiona-naughton @orbeckst 
- Hackathon Introduction & Project Setup @yuxuanzhuang 

Were there any slides that would be good to add for the "Everything You Wanted to Know About MDAnalysis, But Didn't Dare Ask!" session @richardjgowers, @yuxuanzhuang, @hmacdope?

### CODE REVIEW

**Review by orbeckst — APPROVED** [review]
lgtm, thanks for putting it all together

**Comment by richardjgowers** [comment]
@jennaswa https://docs.google.com/presentation/d/1iEsWv36eUl7djWuCsBGaKGFIB6uyiHv4JoPgNzUGwXs/edit

That was my third, yuxuan had a notebook and Hugo had a blogpost he went through

**Comment by jennaswa** [comment]
> @jennaswa https://docs.google.com/presentation/d/1iEsWv36eUl7djWuCsBGaKGFIB6uyiHv4JoPgNzUGwXs/edit
> 
> That was my third, yuxuan had a notebook and Hugo had a blogpost he went through

Great, thanks! If everyone could commit their materials/links/etc that you want included to this PR, that‘d be super helpful

**Review by yuxuanzhuang — APPROVED** [review]
added hackathon showcase and "Everything You Wanted to Know" parallel analysis session notebook

**Comment by jennaswa** [comment]
@hmacdope - could you please provide the link to the blog post so we can add it to the "everything you wanted to know" session in the README; we can then probably go ahead and merge this PR. Thanks!

**Comment by hmacdope** [comment]
@jennaswa we can just use Lawson's GSOC blog post: https://www.mdanalysis.org/2024/08/03/gsoc2024_woods

**Pull request merged**
